#!/usr/bin/env python3
"""Extract a curated subset of the claudepix mascot animations.

Source: clawdmeter-win/firmware/src/splash_animations.h (13 animations, generated
for an ESP32-S3 / LVGL build with the frame data in RAM-resident `static const`).

This pulls out just the few animations we show on the SmallTV and re-emits them
with PROGMEM so the ~33 KB of frame data lives in flash instead of the ESP8266's
~40 KB heap. The renderer reads cells/palette/holds back with pgm_read_*.

Run from the repo root:  python tools/extract_mascot.py
Output: src/mascot_frames.h  (do not hand-edit — re-run this instead)
"""

import re
import sys
from pathlib import Path

SRC = Path("../clawdmeter-win/firmware/src/splash_animations.h")
OUT = Path("src/mascot_frames.h")

# (display name, source variable prefix, burn-rate group 0=idle..3=heavy)
CHOSEN = [
    ("idle breathe", "splash_idle_breathe", 0),
    ("idle blink",   "splash_idle_blink",   0),
    ("work coding",  "splash_work_coding",  1),
    ("dance sway",   "splash_dance_sway",   2),
    ("dance bounce", "splash_dance_bounce", 3),
]


def grab(text: str, pattern: str, name: str) -> str:
    m = re.search(pattern, text, re.DOTALL)
    if not m:
        sys.exit(f"ERROR: could not find {name} in {SRC}")
    return m.group(0)


def main() -> None:
    if not SRC.exists():
        sys.exit(f"ERROR: source not found: {SRC.resolve()}")
    text = SRC.read_text()

    blocks = []
    table = []
    for disp, src_prefix, group in CHOSEN:
        dst_prefix = src_prefix.replace("splash_", "mascot_", 1)

        palette = grab(text, rf"static const uint16_t {src_prefix}_palette\[10\] = \{{.*?\}};",
                       f"{src_prefix}_palette")
        frames = grab(text, rf"static const uint8_t {src_prefix}_frames\[(\d+)\]\[400\] = \{{.*?\n\}};",
                      f"{src_prefix}_frames")
        holds = grab(text, rf"static const uint16_t {src_prefix}_holds\[\d+\] = \{{.*?\}};",
                     f"{src_prefix}_holds")

        frame_count = int(re.search(rf"{src_prefix}_frames\[(\d+)\]", frames).group(1))

        # Rename splash_ -> mascot_. Only the big frame arrays go in PROGMEM (read
        # one byte at a time with pgm_read_byte). The 16-bit palette/holds tables
        # stay in RAM: on the ESP8266 a 16-bit load (l16ui) from flash/irom faults,
        # so reading uint16_t PROGMEM via pgm_read_word crashes — keep them in RAM
        # and index them directly.
        def rename(s: str) -> str:
            return s.replace(src_prefix, dst_prefix)
        def progmem(s: str) -> str:
            return re.sub(r"\] = \{", "] PROGMEM = {", rename(s), count=1)

        blocks.append(rename(palette))    # RAM (uint16_t)
        blocks.append(progmem(frames))    # PROGMEM (uint8_t, pgm_read_byte)
        blocks.append(rename(holds))      # RAM (uint16_t)
        blocks.append("")

        table.append(
            f'    {{"{disp}", {group}, {frame_count}, '
            f"{dst_prefix}_palette, {dst_prefix}_frames, {dst_prefix}_holds}},"
        )

    header = f"""// mascot_frames.h - GENERATED by tools/extract_mascot.py. Do not edit by hand.
//
// Curated subset of the claudepix 20x20 pixel-art creature animations for the
// ESP8266. The big frame arrays live in PROGMEM (flash, read with pgm_read_byte);
// the small 16-bit palette/holds tables stay in RAM (a 16-bit load from flash
// faults on this chip).
// Source: clawdmeter-win/firmware/src/splash_animations.h (https://claudepix.vercel.app)
// Each animation: a 10-entry RGB565 palette, N frames of 20x20 cells (values 0..9
// index the palette), and N per-frame hold times in ms.
#pragma once
#include <stdint.h>
#include <pgmspace.h>

// These mirror the constants in Mascot.h (guarded so either include order works).
#ifndef MASCOT_PALETTE_SIZE
#define MASCOT_PALETTE_SIZE 10
#endif
#ifndef MASCOT_GRID
#define MASCOT_GRID         20
#endif

typedef struct {{
    const char     *name;
    uint8_t         group;        // burn-rate tier: 0 idle, 1 normal, 2 active, 3 heavy
    uint16_t        frame_count;
    const uint16_t *palette;      // RAM, MASCOT_PALETTE_SIZE entries (16-bit irom reads fault)
    const uint8_t (*frames)[400]; // PROGMEM, frame_count x 400 cells (read via pgm_read_byte)
    const uint16_t *holds;        // RAM, frame_count hold times (ms)
}} MascotAnim;

{chr(10).join(blocks)}
#define MASCOT_ANIM_COUNT {len(CHOSEN)}
static const MascotAnim mascot_anims[MASCOT_ANIM_COUNT] = {{
{chr(10).join(table)}
}};
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header)
    size = OUT.stat().st_size
    print(f"Wrote {OUT} ({size//1024} KB, {len(CHOSEN)} animations)")


if __name__ == "__main__":
    main()
