#!/usr/bin/env python3
"""Extract the two full-screen notify animations from the Clawdmeter splash set.

Source: HermannBjorgvin/Clawdmeter firmware/src/splash_animations.h — the official
Anthropic Clawd art, generated for an ESP32-S3 build with the frame data in RAM.

That file does NOT use the claudepix 20x20 layout tools/extract_mascot.py consumes:

    claudepix (mascot_frames.h)     Clawdmeter (splash_animations.h)
    10-entry palette                16-entry palette + palette_count
    frames[N][400], fixed 20x20     frames[N*w*h], per-anim bounding-box crop
    -                               w/h/ox/oy on a shared 55x37 stage
    -                               loop_start/loop_end, category

So this emits its own header rather than appending to the generated mascot one:
palette truncated to 10 entries (both animations use only 4), frames re-emitted
as PROGMEM with the per-animation w/h carried through.

Run from the repo root:  python tools/extract_notify.py [path-to-splash_animations.h]
Output: src/features/notify/notify_frames.h  (do not hand-edit — re-run this)
"""

import re
import sys
from pathlib import Path

DEFAULT_SRC = Path("../Clawdmeter/firmware/src/splash_animations.h")
OUT = Path("src/features/notify/notify_frames.h")
PALETTE_SIZE = 10

# (emitted name, source variable prefix)
CHOSEN = [
    ("done", "splash_jumping_happy"),
    ("waiting", "splash_waving"),
]


def grab(text: str, pattern: str, name: str) -> re.Match:
    m = re.search(pattern, text, re.DOTALL)
    if not m:
        sys.exit(f"ERROR: could not find {name}")
    return m


def numbers(body: str) -> list:
    return [int(v, 0) for v in re.findall(r"0x[0-9a-fA-F]+|\d+", body)]


def main() -> None:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src.exists():
        sys.exit(f"ERROR: source not found: {src.resolve()}")
    text = src.read_text()

    blocks = []
    table = []
    for dst, prefix in CHOSEN:
        entry = grab(text, rf'\{{"[^"]+", "[^"]+", [^}}]*{prefix}_palette[^}}]*\}}',
                     f"{prefix} table entry").group(0)
        fields = entry.split(",")
        w, h = int(fields[2]), int(fields[3])
        frame_count, palette_count = int(fields[6]), int(fields[9])

        palette = numbers(grab(text, rf"{prefix}_palette\[16\] = \{{(.*?)\}};",
                               f"{prefix}_palette").group(1))
        frames = numbers(grab(text, rf"{prefix}_frames\[\d+\] = \{{(.*?)\n\}};",
                              f"{prefix}_frames").group(1))
        holds = numbers(grab(text, rf"{prefix}_holds\[\d+\] = \{{(.*?)\}};",
                             f"{prefix}_holds").group(1))

        cells = w * h
        if len(frames) != frame_count * cells:
            sys.exit(f"ERROR: {prefix} has {len(frames)} cells, expected {frame_count * cells}")
        if len(holds) != frame_count:
            sys.exit(f"ERROR: {prefix} has {len(holds)} holds, expected {frame_count}")
        if palette_count > PALETTE_SIZE or max(frames) >= PALETTE_SIZE:
            sys.exit(f"ERROR: {prefix} needs more than {PALETTE_SIZE} palette entries")

        pal = ",".join(f"0x{c:04X}" for c in palette[:PALETTE_SIZE])
        rows = ",\n    ".join(
            ",".join(str(c) for c in frames[i * cells:(i + 1) * cells])
            for i in range(frame_count))

        blocks.append(f"static const uint16_t notify_{dst}_palette[{PALETTE_SIZE}] = {{{pal}}};")
        blocks.append(f"static const uint8_t notify_{dst}_frames[{frame_count} * {cells}] PROGMEM = {{\n    {rows}\n}};")
        blocks.append(f"static const uint16_t notify_{dst}_holds[{frame_count}] = "
                      f"{{{','.join(str(v) for v in holds)}}};")
        blocks.append("")

        table.append(f'    {{{w}, {h}, {frame_count}, notify_{dst}_palette, '
                     f"notify_{dst}_frames, notify_{dst}_holds}},")

    header = f"""// notify_frames.h - GENERATED by tools/extract_notify.py. Do not edit by hand.
// Source: HermannBjorgvin/Clawdmeter firmware/src/splash_animations.h.
// ponytail: frames MUST stay PROGMEM and be read with pgm_read_byte — the ESP8266
// has ~14 KB free heap, and a 16-bit load from flash faults, which is why the
// palette/holds tables are RAM-resident instead.
#pragma once
#include <stdint.h>
#include <pgmspace.h>

#define NOTIFY_PALETTE_SIZE {PALETTE_SIZE}

typedef struct {{
    uint8_t         w, h;
    uint16_t        frame_count;
    const uint16_t *palette;      // RAM, NOTIFY_PALETTE_SIZE entries
    const uint8_t  *frames;       // PROGMEM, frame_count x (w*h) cells
    const uint16_t *holds;        // RAM, frame_count hold times (ms)
}} NotifyAnim;

{chr(10).join(blocks)}
#define NOTIFY_ANIM_COUNT {len(CHOSEN)}
{chr(10).join(f"#define NOTIFY_ANIM_{d.upper()} {i}" for i, (d, _) in enumerate(CHOSEN))}
static const NotifyAnim notify_anims[NOTIFY_ANIM_COUNT] = {{
{chr(10).join(table)}
}};
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header)
    print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KB, {len(CHOSEN)} animations)")


if __name__ == "__main__":
    main()
